
repos:
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-yaml

- repo: https://github.com/asottile/pyupgrade
  rev: v2.18.3
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]

- repo: local
  hooks:
  - id: docker-clang-format
    name: Docker Clang Format
    language: docker_image
    types:
    - c++
    - c
    entry: unibeautify/clang-format:latest
    args:
    - -style=file
    - -i
