name: pvfinder
channels:
    - conda-forge
dependencies:
    - root
    - pythia8
    - pandas
    - jupyterlab
    - pytorch-cpu
    - numpy
    - h5py
    - numba
    - tqdm
    - scipy
    - matplotlib
