name: pvfindergpu
channels:
    - pytorch
    - conda-forge
dependencies:
    - python>=3.6
    - h5py
    - jupyterlab
    - matplotlib
    - nb_conda_kernels
    - numba
    - numpy
    - pandas
    - pythia8
    - root
    - scipy
    - tqdm
    - uproot
      # From pytorch
    - cudatoolkit=9.0
    - pytorch
    - torchvision
