name: pvfindergpu
channels:
    - pytorch
    - conda-forge
dependencies:
    - python>=3.6
    - cmake
    - h5py
    - jupyterlab
    - matplotlib
    - ipympl
    - nb_conda_kernels
    - ninja
    - numba<0.46
    - numpy
    - pandas
    - pytest
    - pythia8
    - root
    - scipy
    - tqdm
    - uproot
      # From pytorch
    - cudatoolkit=9.0
    - pytorch
    - torchvision
