name: pvfindergpu
channels:
    - pytorch
    - conda-forge
dependencies:
    - python>=3.8
    - awkward<1
    - cmake
    - h5py
    - ipympl
    - jupyterlab
    - line_profiler
    - matplotlib
    - nb_conda_kernels
    - ninja
    - numba
    - numpy
    - pandas
    - pytables
    - pytest
    - pythia8
    - root<6.24.00
    - scipy
    - tqdm
    - uproot<4
      # From pytorch
    - cudatoolkit
    - pytorch
    - torchvision
